
# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python BNC-MIB

FILENAME = "mibs/BNC.MIB"

MIB = {
    "moduleName": "BNC-MIB",

    "BNC-MIB": {
        "nodetype": "module",
        "language": "SMIv2",
        "organization":
            """Motorola Connected Home Solutions""",
        "contact":
            """Motorola Technical Response Center
Inside USA     1-888-944-HELP (1-888-044-4357)
Outside USA    1-215-323-0044
TRC Hours:
Monday through Friday 8am - 7pm Eastern Standard Time
Saturdays            10am - 5pm Eastern Standard Time""",
        "description":
            """The MIB module for the Broadcast Network
Controller (BNC).""",
        "revisions": (
            {
                "date": "2009-12-18 01:00",
                "description":
                    """[Revision added by libsmi due to a LAST-UPDATED clause.]""",
            },
        ),
        "identity node": "bnc",
    },

    "imports": (
        {"module": "SNMPv2-SMI", "name": "OBJECT-TYPE"},
        {"module": "SNMPv2-SMI", "name": "NOTIFICATION-TYPE"},
        {"module": "SNMPv2-SMI", "name": "Gauge32"},
        {"module": "SNMPv2-TC", "name": "RowStatus"},
        {"module": "SNMPv2-TC", "name": "DisplayString"},
        {"module": "SNMPv2-TC", "name": "DateAndTime"},
        {"module": "SNMPv2-TC", "name": "TruthValue"},
        {"module": "", "name": "giproducts"},
        {"module": "", "name": "trapIdentifier"},
        {"module": "", "name": "trapSequenceId"},
        {"module": "", "name": "trapNetworkElemModelNumber"},
        {"module": "", "name": "trapNetworkElemSerialNum"},
        {"module": "", "name": "trapPerceivedSeverity"},
        {"module": "", "name": "trapNetworkElemOperState"},
        {"module": "", "name": "trapNetworkElemAlarmStatus"},
        {"module": "", "name": "trapNetworkElemAdminState"},
        {"module": "", "name": "trapNetworkElemAvailStatus"},
        {"module": "", "name": "trapText"},
        {"module": "", "name": "trapNETrapLastTrapTimeStamp"},
        {"module": "", "name": "trapChangedObjectId"},
        {"module": "", "name": "trapAdditionalInfoInteger1"},
        {"module": "", "name": "trapAdditionalInfoInteger2"},
        {"module": "", "name": "trapAdditionalInfoInteger3"},
    ),

    "nodes": {
        "bnc": {
            "nodetype": "node",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102",
            "status": "current",
        },  # node
        "bncSystem": {
            "nodetype": "node",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1",
        },  # node
        "bncIdNumber": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.1",
            "status": "current",
            "syntax": {
                "type": {"module": "", "name": "Integer32"},
            },
            "access": "readonly",
            "description":
                """This is the BNC ID number allocated to the BNC by the license
key.  For an unlicensed BNC application (e.g.; BNC Lite), the
agent shall return a value of 1.""",
        },  # scalar
        "bncPlatformHealthStatus": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.2",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "ok": {
                        "nodetype": "namednumber",
                        "number": "0"
                    },
                    "unknown": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "warning": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "error": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "fatal": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                },
            },
            "access": "readonly",
            "description":
                """The health of the hardware platform on which the BNC server is
running.""",
        },  # scalar
        "bncPlatformHealthStatusLastChange": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.3",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DateAndTime"},
            },
            "access": "readonly",
            "description":
                """The timestamp of when the platform health status last changed.""",
        },  # scalar
        "bncSiteTable": {
            "nodetype": "table",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.50",
            "status": "current",
            "description":
                """A table of the sites under the control of the BNC. If the BNC is
configured as a Decoder Management BNC server in split operation
then this table will contain no rows.""",
        },  # table
        "bncSiteEntry": {
            "nodetype": "row",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.50.1",
            "status": "current",
            "linkage": [
                "bncSiteIndex",
            ],
            "description":
                """A conceptual row in bncSiteTable.""",
        },  # row
        "bncSiteIndex": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.50.1.1",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "noaccess",
            "description":
                """The user assigned Site ID, which is used as an index into the table
of Sites under the control of the BNC. A BNC server may control one or
more Sites.""",
        },  # column
        "bncSiteName": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.50.1.2",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """Unique user-assigned name for the Site.""",
        },  # column
        "bncSiteHealthStatus": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.50.1.3",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "ok": {
                        "nodetype": "namednumber",
                        "number": "0"
                    },
                    "unknown": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "warning": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "error": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "fatal": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                },
            },
            "access": "readonly",
            "description":
                """Health status of this Site.  At startup, this 
bncSiteHealthStatus defaults to 'unknown' (1).
The bncSiteHealthStatus reflects the highest health
status value of all network elements within the site.""",
        },  # column
        "bncSiteHealthStatusLastChange": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.50.1.4",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DateAndTime"},
            },
            "access": "readonly",
            "description":
                """Time the last modification was made to this BNC Site.""",
        },  # column
        "bncGroupTable": {
            "nodetype": "table",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.51",
            "status": "current",
            "description":
                """A table of the network element groups under the control of the BNC.
If the BNC is configured as a Decoder Management BNC server in split
operation then this table will contain no rows.""",
        },  # table
        "bncGroupEntry": {
            "nodetype": "row",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.51.1",
            "status": "current",
            "linkage": [
                "bncSiteIndexG",
                "bncGroupIndex",
            ],
            "description":
                """A row in bncGroupTable.""",
        },  # row
        "bncSiteIndexG": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.51.1.1",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "noaccess",
            "description":
                """The BNC assigned Site ID associated with this group.""",
        },  # column
        "bncGroupIndex": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.51.1.2",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "noaccess",
            "description":
                """The network element group ID, which is used as an index into
the table of network element groups under control of the BNC.
The network element group ID is automatically assigned during
group creation. A BNC server can control more than one network
element group.""",
        },  # column
        "bncGroupName": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.51.1.3",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """The unique user-assigned name for the network element group.""",
        },  # column
        "bncGroupHealthStatus": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.51.1.4",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "ok": {
                        "nodetype": "namednumber",
                        "number": "0"
                    },
                    "unknown": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "warning": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "error": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "fatal": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                },
            },
            "access": "readonly",
            "description":
                """Status of this network element group.  At startup, this 
bncGroupHealthStatus defaults to 'unknown' (1).
The bncGroupHealthStatus reflects the highest health status
value of all network elements within the network element group.""",
        },  # column
        "bncGroupHealthStatusLastChange": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.51.1.5",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DateAndTime"},
            },
            "access": "readonly",
            "description":
                """Time the last modification was made to this BNC network
element group.""",
        },  # column
        "bncElementTable": {
            "nodetype": "table",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52",
            "status": "current",
            "description":
                """A table of the network elements under control of the BNC. If the
BNC is configured as a Decoder Management BNC server in split
operation then this table will contain no rows.""",
        },  # table
        "bncElementEntry": {
            "nodetype": "row",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1",
            "status": "current",
            "linkage": [
                "bncSiteIndexE",
                "bncGroupIndexE",
                "bncElementIndex",
            ],
            "description":
                """A row in BncElementTable.""",
        },  # row
        "bncSiteIndexE": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.1",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "noaccess",
            "description":
                """The BNC assigned Site ID associated with this Element.""",
        },  # column
        "bncGroupIndexE": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.2",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "noaccess",
            "description":
                """The BNC assigned Network Element Group ID associated with this Element.""",
        },  # column
        "bncElementIndex": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.3",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "noaccess",
            "description":
                """The network element ID number, which is an index into the table
of network elements under the control of the BNC. The network
element ID number is automatically assigned during network element
creation.""",
        },  # column
        "bncElementName": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.4",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """Unique user-assigned name for the network element.""",
        },  # column
        "bncElementIpAddress": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.5",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-SMI", "name": "IpAddress"},
            },
            "access": "readonly",
            "description":
                """The IP address of the network element.""",
        },  # column
        "bncElementType": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.6",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "se1010": {
                        "nodetype": "namednumber",
                        "number": "0"
                    },
                    "se2000": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "tmx": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "dataServer": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "adServer": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                    "sem": {
                        "nodetype": "namednumber",
                        "number": "5"
                    },
                    "opRouter": {
                        "nodetype": "namednumber",
                        "number": "6"
                    },
                    "ipRouter": {
                        "nodetype": "namednumber",
                        "number": "7"
                    },
                    "se4010": {
                        "nodetype": "namednumber",
                        "number": "8"
                    },
                    "se4100": {
                        "nodetype": "namednumber",
                        "number": "9"
                    },
                    "se5010": {
                        "nodetype": "namednumber",
                        "number": "10"
                    },
                    "se5100": {
                        "nodetype": "namednumber",
                        "number": "11"
                    },
                    "modulator": {
                        "nodetype": "namednumber",
                        "number": "12"
                    },
                    "se3000": {
                        "nodetype": "namednumber",
                        "number": "13"
                    },
                    "se6000-6601": {
                        "nodetype": "namednumber",
                        "number": "14"
                    },
                    "sencoreModulator": {
                        "nodetype": "namednumber",
                        "number": "15"
                    },
                    "rE-FPM": {
                        "nodetype": "namednumber",
                        "number": "16"
                    },
                    "fPM": {
                        "nodetype": "namednumber",
                        "number": "17"
                    },
                    "dEM": {
                        "nodetype": "namednumber",
                        "number": "18"
                    },
                    "nTPserver": {
                        "nodetype": "namednumber",
                        "number": "19"
                    },
                    "networkSwitch": {
                        "nodetype": "namednumber",
                        "number": "20"
                    },
                    "inputSource": {
                        "nodetype": "namednumber",
                        "number": "21"
                    },
                },
            },
            "access": "readonly",
            "description":
                """Type of network element.""",
        },  # column
        "bncElementRedundancyGroupID": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.7",
            "status": "current",
            "syntax": {
                "type": {"module": "", "name": "Integer32"},
            },
            "access": "readonly",
            "description":
                """The ID of the redundancy group that this network element belongs to. A value of
(-1) indicates that the network element has not been placed in a redundant
configuration.""",
        },  # column
        "bncElementRedundancyGroupName": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.8",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """The name of the redundancy group that this network element belongs to. If the
network element has not been placed into a redundant configuration, an empty
(zero-length) string is returned for this object.""",
        },  # column
        "bncElementRedundancyRole": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.9",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "standAlone": {
                        "nodetype": "namednumber",
                        "number": "0"
                    },
                    "primary": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "backup": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                },
            },
            "access": "readonly",
            "description":
                """Redundancy role of the network element within system. If the network element has
not been placed into a redundant configuration, the value standAlone is returned.
	standAlone  - no redundancy switching is provided for this network element.
	primary		- a redundant network element that is normally providing service.
	backup		- a redundant network element that is switched into service in the
				  event of a failure of a primary network element.""",
        },  # column
        "bncElementRequestedOpState": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.10",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "online": {
                        "nodetype": "namednumber",
                        "number": "0"
                    },
                    "offLine": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                },
            },
            "access": "readonly",
            "description":
                """Requested operational state of this network element by the user.
The user's desired operational state of a network element is represented
in this object.
	online		- operator requests network element to placed online
	offline		- operator requests network element to placed offline.""",
        },  # column
        "bncElementActualOpState": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.11",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "active": {
                        "nodetype": "namednumber",
                        "number": "0"
                    },
                    "standby": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "offLine": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                },
            },
            "access": "readonly",
            "description":
                """Actual operational state of this network element.
The actual operational state of this network element as commanded by the TMX in
its role as the redundancy controller within the system is represented by this
object. The actual operational state may differ from the requested operational state
if the network element has faulted or cannot provide active service.
	active		- provide service
	standby 	- ready to provide service in the event of the failure of an
			  	  associated primary device.
	offline		- not available for use.""",
        },  # column
        "bncElementHealthStatus": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.12",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "ok": {
                        "nodetype": "namednumber",
                        "number": "0"
                    },
                    "unknown": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "warning": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "error": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "fatal": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                },
            },
            "access": "readonly",
            "description":
                """Status of this network element.  At startup, this 
alarm status defaults to 'unknown' (1).""",
        },  # column
        "bncElementHealthStatusLastChange": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.13",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DateAndTime"},
            },
            "access": "readonly",
            "description":
                """Time the last modification was made to this network element.""",
        },  # column
        "bncElementPositionID": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.52.1.14",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """A network element identifier that is unique within a single BNC system
and that can be used to identify similar network elements when doing
A:B comparison of two BNC system configurations.""",
        },  # column
        "bncDatabase": {
            "nodetype": "node",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.53",
        },  # node
        "bncDatabaseConnections": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.53.1",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-SMI", "name": "Gauge32"},
            },
            "access": "readonly",
            "description":
                """The current number of database connections.""",
        },  # scalar
        "bncDatabaseImageSize": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.53.2",
            "status": "current",
            "syntax": {
                "type": {"module": "", "name": "Integer32"},
            },
            "access": "readonly",
            "description":
                """The database image size in kilobytes.""",
        },  # scalar
        "bncDatabaseLastBackup": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.53.3",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DateAndTime"},
            },
            "access": "readonly",
            "description":
                """The time of the last database backup.""",
        },  # scalar
        "bncDatabaseNextBackup": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.53.4",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DateAndTime"},
            },
            "access": "readonly",
            "description":
                """The time of the next scheduled backup.""",
        },  # scalar
        "bncDatabaseCheckpoint": {
            "nodetype": "node",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.53.5",
        },  # node
        "bncDatabaseCheckpointTimestamp": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.53.5.1",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DateAndTime"},
            },
            "access": "readonly",
            "description":
                """The time of the last published database checkpoint. If
the optional database checkpoint package is not installed on the
BNC server, this OID is not available.""",
        },  # scalar
        "bncDatabaseCheckpointSourceIP": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.53.5.2",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-SMI", "name": "IpAddress"},
            },
            "access": "readonly",
            "description":
                """The IP address of the BNC server that was the source
of the last published database checkpoint. If the optional database
checkpoint package is not installed on the BNC server, this OID is
not available.""",
        },  # scalar
        "bncDatabaseCheckpointPublish": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.53.5.3",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "TruthValue"},
            },
            "access": "readwrite",
            "description":
                """A value of false(2) disables database checkpoint publishing
on this BNC server, a value of true(1) enables database checkpoint
publishing on this BNC server. If the optinal database checkpoint
package is not installed on the BNC server, this OID is not available.""",
        },  # scalar
        "bncDecoderControl": {
            "nodetype": "node",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.54",
        },  # node
        "bncDecoderControlDataTransmit": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.54.1",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "TruthValue"},
            },
            "access": "readwrite",
            "description":
                """A value of false(2) mutes the transmission of decoder control
data in the output multiplex, a value of true(1) enables the
transmission of decoder control data in the output multiplex. If the
BNC is a MUX management BNC server in split operation, the value of
this OID is undefined when read and writes to it have no effect on the
operation of the MUX management BNC server.""",
        },  # scalar
        "bncDecoderControlChannelDataPublish": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.54.2",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "TruthValue"},
            },
            "access": "readwrite",
            "description":
                """A value of false(2) disables publishing of decoder channel data
from this BNC server, a value of true(1) enables publishing of
decoder channel data from this BNC server.  If the BNC is a MUX
management BNC server in split operation, the value of this OID
is undefined when read and writes to it have no effect on the operation
of the MUX management BNC server.""",
        },  # scalar
        "bncServiceTable": {
            "nodetype": "table",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.55",
            "status": "current",
            "description":
                """A table of the DCII services in an output multiplex generated by the
equipment under the control of the BNC. If the BNC is configured as
a Decoder Management BNC server in split operation then this table
will contain no rows.""",
        },  # table
        "bncServiceEntry": {
            "nodetype": "row",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.55.1",
            "status": "current",
            "linkage": [
                "bncSiteIndexS",
                "bncGroupIndexS",
                "bncServiceIndex",
            ],
            "description":
                """A row in BncServiceTable.""",
        },  # row
        "bncSiteIndexS": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.55.1.1",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "noaccess",
            "description":
                """The BNC assigned Site ID associated with this Service.""",
        },  # column
        "bncGroupIndexS": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.55.1.2",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "noaccess",
            "description":
                """The BNC assigned Network Element Group ID associated with this Service.""",
        },  # column
        "bncServiceIndex": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.55.1.3",
            "status": "current",
            "syntax": {
                "type": {"module": "", "name": "Integer32"},
            },
            "access": "noaccess",
            "description":
                """The MPEG program number of the service, which is an index into
the table of DCII services.""",
        },  # column
        "bncServiceName": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.55.1.4",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """The name of the DCII service.""",
        },  # column
        "bncServiceEncryptionMode": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.55.1.5",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "clear": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "unencrypted": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "fixedkey": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "full_encryption": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                },
            },
            "access": "readonly",
            "description":
                """The current encryption mode of the DCII service.""",
        },  # column
        "bncServicePLADEncryptionMode": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.55.1.6",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "clear": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "unencrypted": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "fixedkey": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "full_encryption": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                },
            },
            "access": "readonly",
            "description":
                """The current PLAD encryption mode of the service.""",
        },  # column
        "bncProgramTable": {
            "nodetype": "table",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56",
            "status": "current",
            "description":
                """A table of the DCII programs in a output multiplex generated by
the equipment under the control of the BNC. If the BNC is configured
as a Decoder Management BNC server in split operation then this table
will contain no rows.""",
        },  # table
        "bncProgramEntry": {
            "nodetype": "row",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1",
            "status": "current",
            "linkage": [
                "bncSiteIndexP",
                "bncGroupIndexP",
                "bncServiceIndexP",
                "bncProgramIndex",
            ],
            "description":
                """A row in the BncProgramTable.""",
        },  # row
        "bncSiteIndexP": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.1",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "noaccess",
            "description":
                """The BNC assigned Site ID associated with this program.""",
        },  # column
        "bncGroupIndexP": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.2",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "noaccess",
            "description":
                """The BNC assigned Network Element Group ID associated with this program.""",
        },  # column
        "bncServiceIndexP": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.3",
            "status": "current",
            "syntax": {
                "type": {"module": "", "name": "Integer32"},
            },
            "access": "noaccess",
            "description":
                """The service number associated with this Program.""",
        },  # column
        "bncProgramIndex": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.4",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "current": {
                        "nodetype": "namednumber",
                        "number": "0"
                    },
                    "next": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                },
            },
            "access": "noaccess",
            "description":
                """The program ID of the DCII program. The program ID may be automatically generated by the BNC
or specified by the user during DCII program creation.""",
        },  # column
        "bncProgramName": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.5",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """The DCII program name.""",
        },  # column
        "bncProgramStartTime": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.6",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DateAndTime"},
            },
            "access": "readonly",
            "description":
                """The start time of the DCII program epoch.""",
        },  # column
        "bncProgramEndTime": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.7",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DateAndTime"},
            },
            "access": "readonly",
            "description":
                """The end time of the DCII program epoch.""",
        },  # column
        "bncProgramCatvTier1": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.8",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "2048"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "2048"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A CATV tier in the range of 0 to 2048. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramCatvTier2": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.9",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "2048"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "2048"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A CATV tier in the range of 0 to 2048. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramCatvTier3": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.10",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "2048"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "2048"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A CATV tier in the range of 0 to 2048. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramCatvTier4": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.11",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "2048"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "2048"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A CATV tier in the range of 0 to 2048. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramCatvTier5": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.12",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "2048"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "2048"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A CATV tier in the range of 0 to 2048. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramCatvTier6": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.13",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "2048"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "2048"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A CATV tier in the range of 0 to 2048. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramCatvTier7": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.14",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "2048"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "2048"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A CATV tier in the range of 0 to 2048. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramCatvTier8": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.15",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "2048"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "2048"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A CATV tier in the range of 0 to 2048. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramDbsTier1": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.16",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "16777215"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "16777215"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A DBS tier in the range of 0 to 16,777,215. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramDbsTier2": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.17",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "16777215"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "16777215"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A DBS tier in the range of 0 to 16,777,215. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramDbsTier3": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.18",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "16777215"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "16777215"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A DBS tier in the range of 0 to 16,777,215. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramDbsTier4": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.19",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "16777215"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "16777215"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A DBS tier in the range of 0 to 16,777,215. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramDbsTier5": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.20",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "16777215"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "16777215"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A DBS tier in the range of 0 to 16,777,215. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramDbsTier6": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.21",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "16777215"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "16777215"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A DBS tier in the range of 0 to 16,777,215. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramDbsTier7": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.22",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "16777215"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "16777215"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A DBS tier in the range of 0 to 16,777,215. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncProgramDbsTier8": {
            "nodetype": "column",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.56.1.23",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "-1",
                            "max": "16777215"
                        },
                    ],
                    "range": {
                        "min": "-1",
                        "max": "16777215"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A DBS tier in the range of 0 to 16,777,215. A value of -1 signifies
that the tier has not been assigned.""",
        },  # column
        "bncSysTraps": {
            "nodetype": "node",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.100",
        },  # node
        "bncEnableTraps": {
            "nodetype": "scalar",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.99",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "enable": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "disable": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                },
            },
            "access": "readonly",
            "description":
                """Indicates whether the agent will send traps whenever a fault
is detected/cleared. If trap receivers are configured,
default is enabled.""",
        },  # scalar
    },  # nodes

    "notifications": {
        "trapBncSiteError": {
            "nodetype": "notification",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.100.1",
            "status": "current",
            "objects": {
                "trapIdentifier": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapSequenceId": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemModelNumber": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemSerialNum": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapPerceivedSeverity": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemOperState": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemAlarmStatus": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemAdminState": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemAvailStatus": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapText": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNETrapLastTrapTimeStamp": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapChangedObjectId": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapAdditionalInfoInteger1": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapAdditionalInfoInteger2": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapAdditionalInfoInteger3": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
            },
            "description":
                """Refer to associated alarm object bncSiteAlarmStatus.  This
trap is issued if an error is detected for a Site within the 
purview of the BNC.

trapText - 'BNC Site error detected'
	
	AdditionalInfo -
	1:  Site ID Number.
	2:  Group ID Number, if relevant.
	3:  NE ID Number, if relevant.""",
        },  # notification
        "trapBncSysError": {
            "nodetype": "notification",
            "moduleName": "BNC-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102.1.100.2",
            "status": "current",
            "objects": {
                "trapIdentifier": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapSequenceId": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemModelNumber": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemSerialNum": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapPerceivedSeverity": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemOperState": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemAlarmStatus": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemAdminState": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNetworkElemAvailStatus": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapText": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapNETrapLastTrapTimeStamp": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapChangedObjectId": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapAdditionalInfoInteger1": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapAdditionalInfoInteger2": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
                "trapAdditionalInfoInteger3": {
                    "nodetype": "object",
                    "module": "BNC-MIB"
                },
            },
            "description":
                """Refer to associated alarm object bncSysAlarmStatus.  This
trap is issued if an error is detected in the BNC.

trapText - 'BNC System error detected'

AdditionalInfo - 
1:  BNC ID Number.
2 and 3 not used.""",
        },  # notification
    },  # notifications

}
