# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python BCS-IDENT-MIB

FILENAME = "mibs/BCS-IDENT-MIB"

MIB = {
    "moduleName": "BCS-IDENT-MIB",

    "BCS-IDENT-MIB": {
        "nodetype": "module",
        "language": "SMIv2",
        "organization":
            """Motorola Connected Home Solutions""",
        "contact":
            """Motorola Technical Response Center
Inside USA     1-888-944-HELP (1-888-944-4357)
Outside USA    1-215-323-0044
TRC Hours:
Monday through Friday 8am - 7pm Eastern Standard Time
Saturdays            10am - 5pm Eastern Standard Time""",
        "description":
            """The SMIv2 MIB module for the MOTOROLA BCS common ident objects.
The MIB Tree for this is shown below.""",
        "revisions": (
            {
                "date": "2006-08-09 08:49",
                "description":
                    """[Revision added by libsmi due to a LAST-UPDATED clause.]""",
            },
        ),
        "identity node": "gi",
    },

    "imports": (
        {"module": "SNMPv2-TC", "name": "DisplayString"},
        {"module": "SNMPv2-SMI", "name": "OBJECT-TYPE"},
        {"module": "SNMPv2-SMI", "name": "MODULE-IDENTITY"},
    ),

    "typedefs": {
        "EntryStatus": {
            "basetype": "Enumeration",
            "valid": {
                "nodetype": "namednumber",
                "number": "1"
            },
            "createRequest": {
                "nodetype": "namednumber",
                "number": "2"
            },
            "underCreation": {
                "nodetype": "namednumber",
                "number": "3"
            },
            "invalid": {
                "nodetype": "namednumber",
                "number": "4"
            },
        },
    },  # typedefs

    "nodes": {
        "gi": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166",
            "status": "current",
        },  # node
        "giproducts": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1",
        },  # node
        "acc4000d": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.1",
        },  # node
        "anicd": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.2",
        },  # node
        "item1000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.4",
        },  # node
        "irt1000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.5",
        },  # node
        "nc1500": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.6",
        },  # node
        "om1000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.7",
        },  # node
        "im1000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.8",
        },  # node
        "mps": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.9",
        },  # node
        "rpd1000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.10",
        },  # node
        "acpStatus": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.11",
        },  # node
        "heartbeat": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.12",
        },  # node
        "entitlementKey": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.13",
        },  # node
        "arpd": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.14",
        },  # node
        "surfBbnh": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.18",
        },  # node
        "sb2100": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.19",
        },  # node
        "sb2100D": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.20",
        },  # node
        "sb2000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.21",
        },  # node
        "saDANIS": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.30",
        },  # node
        "hdd2000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.40",
        },  # node
        "merlin": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.50",
        },  # node
        "sem": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.70",
        },  # node
        "ecmg": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.71",
        },  # node
        "bsiAdapter": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.72",
        },  # node
        "oles": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.73",
        },  # node
        "ne": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.74",
        },  # node
        "tmxCommTrap": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.75",
        },  # node
        "motolockkskdc": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.76",
        },  # node
        "motolockrte": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.77",
        },  # node
        "motolockecmg": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.78",
        },  # node
        "motolockskgpkg": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.79",
        },  # node
        "tmx": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.80",
        },  # node
        "prs": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.81",
        },  # node
        "se2000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.82",
        },  # node
        "dem": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.83",
        },  # node
        "ncs": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.84",
        },  # node
        "ucs": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.85",
        },  # node
        "lmm": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.86",
        },  # node
        "se4000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.87",
        },  # node
        "rc": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.88",
        },  # node
        "netSentry": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.99",
        },  # node
        "sdm": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.100",
        },  # node
        "hfcEms": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.101",
        },  # node
        "bnc": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.102",
        },  # node
        "motolockcm": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.103",
        },  # node
        "ponOa": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.150",
        },  # node
        "mwtea200": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.151",
        },  # node
        "bti": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.200",
        },  # node
        "rfModMIB": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.201",
        },  # node
        "btiIntMIB": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.202",
        },  # node
        "ponEm870": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.210",
        },  # node
        "rpa": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.250",
        },  # node
        "rpc": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.251",
        },  # node
        "dct5000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.300",
        },  # node
        "dct5100": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.301",
        },  # node
        "dct5200": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.302",
        },  # node
        "edfaMIB": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.311",
        },  # node
        "corvusMIB": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.312",
        },  # node
        "oa600": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.313",
        },  # node
        "dsr350f": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.321",
        },  # node
        "radd6000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.400",
        },  # node
        "cs1000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.401",
        },  # node
        "kls": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.402",
        },  # node
        "dac6000": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.403",
        },  # node
        "sdi": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.404",
        },  # node
        "motoIPNSprodID": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.450",
        },  # node
        "ird4500x": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.610",
        },  # node
        "ird4520x": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.1.620",
        },  # node
        "giproxies": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.3",
        },  # node
        "gicommon": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.4",
        },  # node
        "identity": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.4.1",
        },  # node
        "state": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.4.2",
        },  # node
        "traps": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.4.3",
        },  # node
        "logs": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.4.4",
        },  # node
        "motproxies": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.6",
        },  # node
        "bcs": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7",
        },  # node
        "bcsIdent": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1",
        },  # node
        "identSerialNumber": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.1",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """This contains the serial number of the unit.  There is no 
specification of the internal format of the serial number. 
The serial number is entered into either permanent or non-
volatile memory of the unit at the time of manufacture. 
Note - the unit itself supplies the serial number.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identChassisNumber": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.2",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """This contains the chassis number of the unit.  This is
applicable only to a limited number of products, 
currently, only the ITEM-1000.  For products for which
this is not applicable, this will be a null object.
There is no specification of the internal format of 
the chassis number.  The means by which any product
determines its chassis number is to be determined by
each individual product.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identIfIndex": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.3",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "readonly",
            "default": "2147483647",
            "description":
                """This contains the IfIndex of the OAM&P port.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identHardwareVersion": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.4",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """This contains a display string that defines the hardware
version of this particular unit. There is no specification 
of the internal format of the hardware version.  The 
hardware version is entered into the either permanent or 
non-volatile memory of the unit at the time of 
manufacture.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identHardwareFeatures": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.5",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """This contains a display string that defines the features
of this particular unit. There is no specification of the 
internal format of the hardware features.  The hardware
features is entered into the either permanent or 
non-volatile memory of the unit at the time of 
manufacture.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identInventoryCode": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.6",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readwrite",
            "description":
                """This contains a display string that defines the inventory 
code for this unit.
Once an inventory code has been set, it should be kept in 
non-volatile memory.  The unit should only allow this object 
to be set when it is in the 'configuration' mode.  There is 
no specification of the internal format of  the inventory 
Code.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identSoftwareVersion": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.7",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """This contains a display string that defines the current 
version of the software for this unit.  The format of the 
software version is a fully qualified directory name.  This 
value is received by a unit as within a BOOTP response from 
the BOOTP server.  It is available to the network manager 
for applications that track the installed software.  Once 
the software  version has been set, it should be kept in 
non-volatile memory.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identLocationArea": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.8",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readwrite",
            "description":
                """This is different from the MIB II sysLocation variable as it
contains only the location area and does not describe the
precise location.
This contains a display string that defines the area in 
 which the unit is installed.  Location is defined by a set 
 of three objects: 'Area', 'Rack', and 'Shelf'.    These 
 location objects cannot be determined by the unit itself, 
 but can only be determined by the network manager.  It is 
 available to the unit for display on a front panel.  Display 
 of the location on the front panel is useful in validating 
 the configuration established by the network manager.  The 
 unit should only allow this object to be set when it is in 
 the 'configuration' mode.  Once the Location Area has been 
 set, it should be kept in non-volatile memory.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identLocationRack": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.9",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readwrite",
            "description":
                """This contains a display string that defines the rack in
which the unit is installed.  Location is defined by a set
of three objects: 'Area', 'Rack', and 'Shelf'.    These 
location objects cannot be determined by the unit itself,
but can only be determined by the network manager.  It is
available to the unit for display on a front panel.  Display
of the location on the front panel is useful in validating
the configuration established by the network manager.  The
unit should only allow this object to be set when it is in
the 'configuration' mode.  Once the Location Area has been
set, it should be kept in non-volatile memory.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identLocationShelf": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.10",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readwrite",
            "description":
                """This contains a display string that defines the shelf in 
which the unit is installed.  Location is defined by a set 
of three objects: 'Area', 'Rack', and 'Shelf'.    These 
location objects cannot be determined by the unit itself, 
but can only be determined by the network manager.  It is 
available to the unit for display on a front panel.  Display 
of the location on the front panel is useful in validating 
the configuration established by the network manager.  The 
unit should only allow this object to be set when it is in 
the 'configuration' mode.  Once the Location Area has been 
set, it should be kept in non-volatile memory.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identMIBVersion": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.11",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """ The version number of this MIB.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identAgentVersion": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.12",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """The version number of the Agent.""",
            "reference>":
                """ -- """,
        },  # scalar
        "identCommand": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.13",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "restart": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "currentlyRestarting": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "unspecified": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "purgeAndRestart": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                    "currentlyPurgingAndRestarting": {
                        "nodetype": "namednumber",
                        "number": "5"
                    },
                    "purgeNvramAndRestart": {
                        "nodetype": "namednumber",
                        "number": "6"
                    },
                    "currentlyPurgingNvramAndRestarting": {
                        "nodetype": "namednumber",
                        "number": "7"
                    },
                },
            },
            "access": "readwrite",
            "description":
                """This is the command to be executed by the resource
managed by the agent.
The value unspecified is always returned on SNMP
Get/GetNext while the resource is running. If the
restart(1) command is given, currentlyRestarting(2)
is returned while the resource is preparing to
restart (reboot).""",
            "reference>":
                """ -- """,
        },  # scalar
        "identIfExtensionTable": {
            "nodetype": "table",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14",
            "status": "current",
            "description":
                """This table contains extensions to the MIB II ifTable which  contains
the definitions of all interfaces. An ifTable entry may be a board
or just a port on a board. Any ifTable entry can have an extension
in the identIfExtensionTable. The corrsponding entry in that table
will have the identIfIndex = ifIndex. Within the ifTable the presence
of such an entry is indicated by setting the variable ifSpecific
to the OBJECT IDENTIFIER value of identIfExtensionTable. Otherwise
iFSpecific is set to {0 0}.
The ifType - other - is used for all board types not envisoned by
MIB II.""",
            "reference>":
                """ -- """,
        },  # table
        "identIfExtensionEntry": {
            "nodetype": "row",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1",
            "status": "current",
            "linkage": [
                "identIfExtensionIndex",
            ],
            "description":
                """An entry (conceptual row) in the Board Table.""",
            "reference>":
                """ -- """,
        },  # row
        "identIfExtensionIndex": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.1",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "readonly",
            "default": "2147483647",
            "description":
                """Same value as ifIndex of MIB II for the same board.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfSerialNumber": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.2",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """This contains the serial number of the board.  There is no 
specification of the internal format of the serial number.  
The serial number is entered into either permanent or 
non-volatile memory of the unit at the time of manufacture.  
Note - the unit itself supplies the serial number.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfHardwareVersion": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.3",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """This contains a display string that defines the version
of this particular board. There is no specification of the 
internal format of the hardware version.  The hardware
version is entered into the either permanent or 
non-volatile memory of the unit at the time of 
manufacture.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfHardwareFeatures": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.4",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """This contains a display string that defines the features of 
this particular board. There is no specification of the 
internal format of the hardware features.  The hardware 
features is entered into the either permanent or 
non-volatile memory of the unit at the time of manufacture.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfInventoryCode": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.5",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readwrite",
            "description":
                """This contains a display string that defines the inventory 
code for this board.  This is an optional value; if there is 
no inventory code, The unit will respond with a null string.  
Once an inventory code has been set, it should be kept in 
non-volatile memory.  The unit should only allow this object 
to be set when it is in the 'configuration' mode.  There is 
no specification of the internal format of the inventory 
Code.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfFirmwareVersion1": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.6",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """Within a product, there may be several identifiers of such 
firmware, boot proms, kernel versions, flash versions, etc.  
This field (and the 3 that follow) are used to hold the 
identification of these items.  These values must be entered 
into the board at the time of manufacturing.  Unused fields 
are reported as null values. These fields are available to 
the network manager for applications that keep track of the
firmware related identification.  There is no specification 
of the internal format of firmware version identifiers.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfFirmwareVersion2": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.7",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """Firmware related identification field # 2.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfFirmwareVersion3": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.8",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """Firmware related identification field # 3.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfFirmwareVersion4": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.9",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """Firmware related identification field # 4""",
            "reference>":
                """ -- """,
        },  # column
        "identIfSlotId": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.10",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "1",
                            "max": "2147483647"
                        },
                    ],
                    "range": {
                        "min": "1",
                        "max": "2147483647"
                    },
                },
            },
            "access": "readwrite",
            "default": "2147483647",
            "description":
                """This variable identifies the board slot.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfCommand": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.11",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "unspecified": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "reset": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "restart": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "halt": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                },
            },
            "access": "readwrite",
            "description":
                """This is the command to be executed by the resource
managed by the agent.
The value unspecified(10 is always returned on SNMP
Get/GetNext while the other values are set by the manager
and executed by the resource.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfAdministrativeState": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.12",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "locked": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "unlocked": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "shuttingDown": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                },
            },
            "access": "readwrite",
            "description":
                """ The current Adminsitrative state of the interface as defined in
ISO/IEC 10164-2.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfOperationalState": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.13",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "enabled": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "disabled": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                },
            },
            "access": "readonly",
            "description":
                """       The current Operational state of the interface as defined in
ISO/IEC 10164-2""",
            "reference>":
                """ -- """,
        },  # column
        "identIfAlarmStatus": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.14",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "underRepair": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "critical": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "major": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "minor": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                    "alarmOutstanding": {
                        "nodetype": "namednumber",
                        "number": "5"
                    },
                    "idle": {
                        "nodetype": "namednumber",
                        "number": "6"
                    },
                },
            },
            "access": "readwrite",
            "description":
                """       This object defines the Alarm status of the interface
as defined in ISO/IEC 10164-2 and state-machine""",
            "reference>":
                """ -- """,
        },  # column
        "identIfAvailabilityStatus": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.15",
            "status": "current",
            "syntax": {
                "type":                 {
                    "basetype": "Enumeration",
                    "inTest": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "failed": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "powerOff": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "offLine": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                    "offDuty": {
                        "nodetype": "namednumber",
                        "number": "5"
                    },
                    "dependency": {
                        "nodetype": "namednumber",
                        "number": "6"
                    },
                    "degraded": {
                        "nodetype": "namednumber",
                        "number": "7"
                    },
                    "notInstalled": {
                        "nodetype": "namednumber",
                        "number": "8"
                    },
                    "logFull": {
                        "nodetype": "namednumber",
                        "number": "9"
                    },
                    "available": {
                        "nodetype": "namednumber",
                        "number": "10"
                    },
                },
            },
            "access": "readonly",
            "description":
                """       This object controls the Availability status of the interface
as defined in ISO/IEC 10164-2 and state-machine""",
            "reference>":
                """ -- """,
        },  # column
        "identIfSpecific": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.16",
            "status": "current",
            "syntax": {
                "type": {"module": "", "name": "ObjectIdentifier"},
            },
            "access": "readonly",
            "description":
                """ The object identifier of a board type specific
extension to the ifTable if necessary. Otherwise,
identIfSpecific is set to {0 0}.""",
            "reference>":
                """ -- """,
        },  # column
        "identIfEntryStatus": {
            "nodetype": "column",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.14.1.17",
            "status": "current",
            "syntax": {
                "type": {"module": "BCS-IDENT-MIB", "name": "EntryStatus"},
            },
            "access": "readwrite",
            "default": "valid",
            "description":
                """This object is used to create, delete or
modify a row in this table.  To create a
a new network element, this object is initially
set to 'createRequest'.  After completion of the
configuration of the new entry, the  manager
must set the appropriate instance of this object
to the value valid(1) or aborts, setting this object
to invalid(4).  This object must not be set to
'active' unless the following columnar objects
exist in this row:
      identIfExtensionIndex
      identIfSerialNumber
      identIfHardwareVersion
      identIfInventoryCode
      identIfFirmwareVersion1
     identIfSpecific
To delete an existing entry in this table,
the manager must set the appropriate
instance of this object to the value invalid(4).
Creation of an instance of this object has the
effect of creating the supplemental object instances
to complete the conceptual row.  An existing instance
of this entry cannot be created.  If circumstances 
occur which cause an entry to become invalid, the 
agent modifies the value of the appropriate instance 
of this object to invalid(4).  Whenever, the value of 
this object for a particular entry becomes 
invalid(4), the conceptual row for that instance may 
be removed from the table at any time, either
immediately or subsequently.""",
        },  # column
        "identUnitModel": {
            "nodetype": "scalar",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.1.15",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-TC", "name": "DisplayString"},
            },
            "access": "readonly",
            "description":
                """This contains the model of the product.  For example,
the ITEM-1000 would contain 'ITEM1000'. """,
            "reference>":
                """ -- """,
        },  # scalar
        "bcsLogs": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.4",
        },  # node
        "bcsSimulcryptScs": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.7",
        },  # node
        "bcsSimulcryptMux": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.8",
        },  # node
        "bcsDatabase": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.7.11",
        },  # node
        "mea": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.8",
        },  # node
        "addressablecontrol": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.9",
        },  # node
        "acCommon": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.9.1",
        },  # node
        "acSecurity": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.9.2",
        },  # node
        "acServices": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.9.3",
        },  # node
        "acBsi": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.9.4",
        },  # node
        "acOperations": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.9.5",
        },  # node
        "acTopology": {
            "nodetype": "node",
            "moduleName": "BCS-IDENT-MIB",
            "oid": "1.3.6.1.4.1.1166.9.6",
        },  # node
    },  # nodes

}
